module.exports = {
  extends: ['stylelint-config-standard-scss'],
  plugins: ['stylelint-order'],
  rules: {
    // Possible errors - Start
    'color-no-invalid-hex': true,
    'font-family-no-duplicate-names': true,
    'font-family-no-missing-generic-family-keyword': null,
    'named-grid-areas-no-invalid': true,
    'function-linear-gradient-no-nonstandard-direction': true,
    'function-calc-no-unspaced-operator': true,
    'string-no-newline': true,
    'unit-no-unknown': true,
    'custom-property-no-missing-var-function': true,
    'property-no-unknown': true,
    'declaration-block-no-duplicate-properties': true,
    'block-no-empty': true,
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['global', 'horizontal', 'vertical', 'export'],
      },
    ],
    'selector-pseudo-element-no-unknown': true,
    'selector-type-no-unknown': true,
    'media-feature-name-no-unknown': true,
    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: ['function', 'if', 'each', 'include', 'mixin', 'for', 'use'],
      },
    ],
    'comment-no-empty': true,
    'no-descending-specificity': null,
    'no-duplicate-at-import-rules': true,
    'no-duplicate-selectors': true,
    'no-empty-source': true,
    'no-invalid-position-at-import-rule': true,
    'media-feature-range-notation': null, // TODO remove it and rewrite @media without mixins
    // Possible errors - End

    // Limit language features - Start
    'alpha-value-notation': 'number',
    'color-function-notation': 'legacy',
    'color-hex-alpha': 'never',
    'color-named': 'never',
    'length-zero-no-unit': true,
    'shorthand-property-no-redundant-values': true,
    'value-no-vendor-prefix': true,
    'declaration-block-no-redundant-longhand-properties': null,
    'selector-max-pseudo-class': 2,
    'selector-no-qualifying-type': true,
    'at-rule-no-vendor-prefix': true,
    'media-feature-name-no-vendor-prefix': true,
    'at-rule-disallowed-list': ['import'],
    // Limit language features - End

    // Stylistic issues - Start
    'color-hex-length': 'short',
    'function-name-case': ['lower', { ignoreFunctions: ['themedGlobal'] }],
    'function-url-quotes': 'always',
    'selector-attribute-quotes': 'always',
    'comment-empty-line-before': [
      'always',
      { except: ['first-nested'], ignore: ['stylelint-commands'] },
    ],
    'rule-empty-line-before': ['always-multi-line', { ignore: ['after-comment', 'first-nested'] }],
    'declaration-colon-newline-after': null,
    'value-list-comma-newline-after': null,
    'declaration-empty-line-before': null,
    // Stylistic issues - End

    'order/properties-order': [
      [
        'all',
        {
          groupName: 'Псевдоэлементы',
          emptyLineBefore: 'always',
          properties: ['content', 'quotes', 'counter-reset', 'counter-increment'],
        },
        {
          groupName: 'Позиционирование',
          emptyLineBefore: 'always',
          properties: ['position', 'top', 'right', 'bottom', 'left', 'z-index'],
        },
        {
          groupName: 'Блочная модель',
          emptyLineBefore: 'always',
          properties: [
            'display',
            'float',
            'clear',
            'flex-direction',
            'flex-wrap',
            'flex-flow',
            'justify-content',
            'align-items',
            'align-content',
            'columns',
            'column-width',
            'column-count',
            'column-fill',
            'column-gap',
            'column-rule',
            'column-rule-color',
            'column-rule-style',
            'column-rule-width',
            'column-span',
            'visibility',
            'overflow',
            'overflow-x',
            'overflow-y',
            '-webkit-overflow-scrolling',
            'clip',
            'zoom',
            '-ms-flex',
            'flex',
            'flex-grow',
            'flex-shrink',
            'flex-basis',
            'align-self',
            'order',
          ],
        },
        {
          groupName: 'Размеры и отступы',
          emptyLineBefore: 'always',
          properties: [
            'box-sizing',
            'width',
            'min-width',
            'max-width',
            'height',
            'min-height',
            'max-height',
            'margin',
            'margin-left',
            'margin-top',
            'margin-right',
            'margin-bottom',
            'padding',
            'padding-left',
            'padding-top',
            'padding-right',
            'padding-bottom',
          ],
        },
        {
          groupName: 'Таблицы',
          emptyLineBefore: 'always',
          properties: [
            'table-layout',
            'empty-cells',
            'caption-side',
            'border-spacing',
            'border-collapse',
            'list-style',
            'list-style-position',
            'list-style-type',
            'list-style-image',
          ],
        },
        {
          groupName: 'Поведение',
          emptyLineBefore: 'always',
          properties: [
            'resize',
            'cursor',
            'user-select',
            'nav-index',
            'nav-left',
            'nav-up',
            'nav-right',
            'nav-down',
            'contain',
            'will-change',
            'transition',
            'transition-delay',
            'transition-timing-function',
            'transition-duration',
            'transition-property',
            'transform',
            'transform-origin',
            'transform-style',
            'backface-visibility',
            'perspective',
            'perspective-origin',
            'animation',
            'animation-name',
            'animation-duration',
            'animation-play-state',
            'animation-timing-function',
            'animation-delay',
            'animation-iteration-count',
            'animation-direction',
            'animation-fill-mode',
            'direction',
            'text-align',
            'text-align-last',
            'vertical-align',
            'white-space',
            'text-decoration',
            'text-decoration-color',
            'text-decoration-line',
            'text-decoration-style',
            'text-emphasis',
            'text-emphasis-color',
            'text-emphasis-style',
            'text-emphasis-position',
            'text-indent',
            'text-justify',
            'text-transform',
            'letter-spacing',
            'word-spacing',
            'writing-mode',
            'text-outline',
            'text-transform',
            'text-wrap',
            'text-overflow',
            'text-overflow-ellipsis',
            'text-overflow-mode',
            'word-wrap',
            'word-break',
            'tab-size',
            'hyphens',
            'image-rendering',
            'object-fit',
            'object-position',
            'pointer-events',
            'appearance',
          ],
        },
        {
          groupName: 'Оформление',
          emptyLineBefore: 'always',
          properties: [
            'opacity',
            '-ms-interpolation-mode',
            'color',
            'border',
            'border-collapse',
            'border-width',
            'border-style',
            'border-color',
            'border-left',
            'border-left-width',
            'border-left-style',
            'border-left-color',
            'border-top',
            'border-top-width',
            'border-top-style',
            'border-top-color',
            'border-right',
            'border-right-width',
            'border-right-style',
            'border-right-color',
            'border-bottom',
            'border-bottom-width',
            'border-bottom-style',
            'border-bottom-color',
            'border-radius',
            'border-top-left-radius',
            'border-top-right-radius',
            'border-bottom-right-radius',
            'border-bottom-left-radius',
            'border-image',
            'border-image-source',
            'border-image-slice',
            'border-image-width',
            'border-image-outset',
            'border-image-repeat',
            'outline',
            'outline-width',
            'outline-style',
            'outline-color',
            'outline-offset',
            'background',
            'background-color',
            'background-image',
            'background-repeat',
            'background-attachment',
            'background-position',
            'background-position-x',
            'background-position-y',
            'background-clip',
            'background-origin',
            'background-size',
            'box-decoration-break',
            'box-shadow',
            'text-shadow',
            'filter',
          ],
        },
        {
          groupName: 'Шрифт',
          emptyLineBefore: 'always',
          properties: [
            'font',
            'font-family',
            'font-size',
            'font-weight',
            'font-style',
            'font-variant',
            'font-size-adjust',
            'font-stretch',
            'font-effect',
            'font-emphasize',
            'font-emphasize-position',
            'font-emphasize-style',
            'font-smooth',
            'line-height',
          ],
        },
        {
          groupName: 'Печать',
          emptyLineBefore: 'always',
          properties: [
            'marks',
            'orphans',
            'page-break-after',
            'page-break-before',
            'page-break-inside',
            'widows',
          ],
        },
      ],
      {
        unspecified: 'bottomAlphabetical',
      },
    ],
  },
};
