import * as M from './mobx/model';

export const CATEGORIES_SET = new Set([
  'terms',
  'obligations',
  'traffic_lights',
  'emergency_signals',
  'start_of_movements',
  'transport_location',
  'speed',
  'overtake',
  'parking',
  'equal_intersections',
  'regulated_intersections',
  'unregulated_intersections',
  'railway',
  'motorway',
  'external_lights',
  'towing',
  'people_transportation',
  'cargo_transportation',
  'warning_signs',
  'prohibition_signs',
  'prescriptive_signs',
  'additional_signs',
  'road_markers',
  'exploitation',
  'identification_signs',
  'auto_control',
  'medical_aid',
]);

export const DEFAULT_CATEGORIES_DATA: Record<M.Category, M.QuestionData[]> = {
  terms: [],
  obligations: [],
  traffic_lights: [],
  emergency_signals: [],
  start_of_movements: [],
  transport_location: [],
  speed: [],
  overtake: [],
  parking: [],
  equal_intersections: [],
  regulated_intersections: [],
  unregulated_intersections: [],
  railway: [],
  motorway: [],
  external_lights: [],
  towing: [],
  people_transportation: [],
  cargo_transportation: [],
  warning_signs: [],
  prohibition_signs: [],
  prescriptive_signs: [],
  additional_signs: [],
  road_markers: [],
  exploitation: [],
  identification_signs: [],
  auto_control: [],
  medical_aid: [],
};

export const DEFAULT_QUIZ_QUESTIONS_AMOUNT = 20;

export const MAX_WRONG_ANSWERS = 2;
